"""initial schema

Revision ID: 152b75a239f1
Revises: 
Create Date: 2026-08-30 18:19:58.457178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152b75a239f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Commission_Rate_History',
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('petrol', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('diesel', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('oil', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('oil_packet', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('oil_cane', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effective_from')
    )
    op.create_table('Credit_Customers',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Employees',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('father_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Expense_Days',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('Lubricant_Products',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), server_default=sa.text("'Pcs'"), nullable=False),
    sa.Column('packaging', sa.Text(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("packaging IN ('packet', 'cane')", name='ck_lubricant_products_packaging'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Offer_Sends',
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Stations',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('dealer_type', sa.Text(), nullable=True),
    sa.Column('sap_no', sa.Text(), nullable=True),
    sa.Column('gstin', sa.Text(), nullable=True),
    sa.Column('dealer_name', sa.Text(), nullable=True),
    sa.Column('address_lines', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('mobiles', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('audit_contact_email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default=sa.text("'staff'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'manager', 'staff')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Attendance_Records',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('one_shift', 'double_shift', 'absent', 'leave', 'duty_off')", name='ck_attendance_records_status'),
    sa.ForeignKeyConstraint(['employee_id'], ['Employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_records_employee_date')
    )
    op.create_index('idx_attendance_employee_date', 'Attendance_Records', ['employee_id', 'date'], unique=False)
    op.create_table('Credit_Customer_Bills',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('uploaded_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Credit_Customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Credit_Customer_Bills_customer_id'), 'Credit_Customer_Bills', ['customer_id'], unique=False)
    op.create_table('Employee_Salary_History',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['Employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'effective_from', name='uq_employee_salary_history')
    )
    op.create_index('idx_salary_history_employee', 'Employee_Salary_History', ['employee_id', 'effective_from'], unique=False)
    op.create_table('Expense_Items',
    sa.Column('expense_day_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_day_id'], ['Expense_Days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expense_items_day', 'Expense_Items', ['expense_day_id'], unique=False)
    op.create_table('Fuel_Entries',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pump_key', sa.Text(), nullable=False),
    sa.Column('shift_number', sa.SmallInteger(), nullable=False),
    sa.Column('internal_only', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('cane_oil_offer', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("pump_key IN ('pump1', 'pump2')", name='ck_fuel_entries_pump_key'),
    sa.CheckConstraint("status IN ('draft', 'final')", name='ck_fuel_entries_status'),
    sa.CheckConstraint('shift_number IN (1, 2, 3)', name='ck_fuel_entries_shift_number'),
    sa.ForeignKeyConstraint(['employee_id'], ['Employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'pump_key', 'shift_number', name='uq_fuel_entries_date_pump_shift')
    )
    op.create_index('idx_fuel_entries_date', 'Fuel_Entries', ['date'], unique=False)
    op.create_index('idx_fuel_entries_employee', 'Fuel_Entries', ['employee_id'], unique=False)
    op.create_index('idx_fuel_entries_pump_date', 'Fuel_Entries', ['pump_key', 'date'], unique=False)
    op.create_table('Lubricant_Price_History',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Lubricant_Products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'effective_from', name='uq_lubricant_price_history')
    )
    op.create_index('idx_lubricant_price_history_product', 'Lubricant_Price_History', ['product_id', 'effective_from'], unique=False)
    op.create_table('Lubricant_Purchase_History',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Lubricant_Products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lubricant_purchase_history_product', 'Lubricant_Purchase_History', ['product_id', 'date'], unique=False)
    op.create_table('Offer_Send_Recipients',
    sa.Column('offer_send_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Credit_Customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_send_id'], ['Offer_Sends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_send_id', 'customer_id', name='uq_offer_send_recipients_send_customer')
    )
    op.create_index('idx_offer_send_recipients_customer', 'Offer_Send_Recipients', ['customer_id'], unique=False)
    op.create_index('idx_offer_send_recipients_send', 'Offer_Send_Recipients', ['offer_send_id'], unique=False)
    op.create_table('Refresh_Tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Refresh_Tokens_token_hash'), 'Refresh_Tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_Refresh_Tokens_user_id'), 'Refresh_Tokens', ['user_id'], unique=False)
    op.create_table('Credit_Ledger_Entries',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('fuel_type', sa.Text(), nullable=True),
    sa.Column('litres', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_fuel_entry_id', sa.UUID(), nullable=True),
    sa.Column('bill_file_name', sa.Text(), nullable=True),
    sa.Column('bill_file_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("fuel_type IS NULL OR fuel_type IN ('petrol', 'diesel', 'oil')", name='ck_credit_ledger_entries_fuel_type'),
    sa.CheckConstraint("type IN ('credit', 'payment')", name='ck_credit_ledger_entries_type'),
    sa.ForeignKeyConstraint(['customer_id'], ['Credit_Customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_fuel_entry_id'], ['Fuel_Entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_ledger_entries_customer', 'Credit_Ledger_Entries', ['customer_id', 'date'], unique=False)
    op.create_table('Employee_Credits',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_fuel_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['Employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_fuel_entry_id'], ['Fuel_Entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_credits_employee', 'Employee_Credits', ['employee_id', 'date'], unique=False)
    op.create_table('Fuel_Entry_Bills',
    sa.Column('fuel_entry_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('uploaded_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['fuel_entry_id'], ['Fuel_Entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fuel_entry_bills_entry', 'Fuel_Entry_Bills', ['fuel_entry_id'], unique=False)
    op.create_table('Fuel_Entry_Oil_Rows',
    sa.Column('fuel_entry_id', sa.UUID(), nullable=False),
    sa.Column('row_type', sa.Text(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('stock_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stock_rate', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("row_type IN ('pocket', 'cane')", name='ck_fuel_entry_oil_rows_row_type'),
    sa.ForeignKeyConstraint(['fuel_entry_id'], ['Fuel_Entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['Lubricant_Products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fuel_entry_oil_rows_entry', 'Fuel_Entry_Oil_Rows', ['fuel_entry_id'], unique=False)
    op.create_index('idx_fuel_entry_oil_rows_product', 'Fuel_Entry_Oil_Rows', ['product_id'], unique=False)
    op.create_table('Fuel_Readings',
    sa.Column('fuel_entry_id', sa.UUID(), nullable=False),
    sa.Column('fuel_type', sa.Text(), nullable=False),
    sa.Column('nozzle', sa.Text(), nullable=False),
    sa.Column('opening', sa.Numeric(precision=12, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('closing', sa.Numeric(precision=12, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('testing', sa.Numeric(precision=10, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("fuel_type IN ('petrol', 'diesel', 'oil')", name='ck_fuel_readings_fuel_type'),
    sa.CheckConstraint("nozzle IN ('nozzle1', 'nozzle2')", name='ck_fuel_readings_nozzle'),
    sa.ForeignKeyConstraint(['fuel_entry_id'], ['Fuel_Entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuel_entry_id', 'fuel_type', 'nozzle', name='uq_fuel_readings_entry_type_nozzle')
    )
    op.create_index('idx_fuel_readings_entry', 'Fuel_Readings', ['fuel_entry_id'], unique=False)
    op.create_table('Payment_Lines',
    sa.Column('fuel_entry_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('type', sa.Text(), server_default=sa.text("'cash'"), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("type IN ('cash', 'credit', 'employee_credit')", name='ck_payment_lines_type'),
    sa.ForeignKeyConstraint(['customer_id'], ['Credit_Customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['Employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fuel_entry_id'], ['Fuel_Entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_lines_customer', 'Payment_Lines', ['customer_id'], unique=False)
    op.create_index('idx_payment_lines_employee', 'Payment_Lines', ['employee_id'], unique=False)
    op.create_index('idx_payment_lines_entry', 'Payment_Lines', ['fuel_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_lines_entry', table_name='Payment_Lines')
    op.drop_index('idx_payment_lines_employee', table_name='Payment_Lines')
    op.drop_index('idx_payment_lines_customer', table_name='Payment_Lines')
    op.drop_table('Payment_Lines')
    op.drop_index('idx_fuel_readings_entry', table_name='Fuel_Readings')
    op.drop_table('Fuel_Readings')
    op.drop_index('idx_fuel_entry_oil_rows_product', table_name='Fuel_Entry_Oil_Rows')
    op.drop_index('idx_fuel_entry_oil_rows_entry', table_name='Fuel_Entry_Oil_Rows')
    op.drop_table('Fuel_Entry_Oil_Rows')
    op.drop_index('idx_fuel_entry_bills_entry', table_name='Fuel_Entry_Bills')
    op.drop_table('Fuel_Entry_Bills')
    op.drop_index('idx_employee_credits_employee', table_name='Employee_Credits')
    op.drop_table('Employee_Credits')
    op.drop_index('idx_credit_ledger_entries_customer', table_name='Credit_Ledger_Entries')
    op.drop_table('Credit_Ledger_Entries')
    op.drop_index(op.f('ix_Refresh_Tokens_user_id'), table_name='Refresh_Tokens')
    op.drop_index(op.f('ix_Refresh_Tokens_token_hash'), table_name='Refresh_Tokens')
    op.drop_table('Refresh_Tokens')
    op.drop_index('idx_offer_send_recipients_send', table_name='Offer_Send_Recipients')
    op.drop_index('idx_offer_send_recipients_customer', table_name='Offer_Send_Recipients')
    op.drop_table('Offer_Send_Recipients')
    op.drop_index('idx_lubricant_purchase_history_product', table_name='Lubricant_Purchase_History')
    op.drop_table('Lubricant_Purchase_History')
    op.drop_index('idx_lubricant_price_history_product', table_name='Lubricant_Price_History')
    op.drop_table('Lubricant_Price_History')
    op.drop_index('idx_fuel_entries_pump_date', table_name='Fuel_Entries')
    op.drop_index('idx_fuel_entries_employee', table_name='Fuel_Entries')
    op.drop_index('idx_fuel_entries_date', table_name='Fuel_Entries')
    op.drop_table('Fuel_Entries')
    op.drop_index('idx_expense_items_day', table_name='Expense_Items')
    op.drop_table('Expense_Items')
    op.drop_index('idx_salary_history_employee', table_name='Employee_Salary_History')
    op.drop_table('Employee_Salary_History')
    op.drop_index(op.f('ix_Credit_Customer_Bills_customer_id'), table_name='Credit_Customer_Bills')
    op.drop_table('Credit_Customer_Bills')
    op.drop_index('idx_attendance_employee_date', table_name='Attendance_Records')
    op.drop_table('Attendance_Records')
    op.drop_table('Users')
    op.drop_table('Stations')
    op.drop_table('Offer_Sends')
    op.drop_table('Lubricant_Products')
    op.drop_table('Expense_Days')
    op.drop_table('Employees')
    op.drop_table('Credit_Customers')
    op.drop_table('Commission_Rate_History')
    # ### end Alembic commands ###
